### ISSUE TITLE
500 errors when using wildcards in `/api/v1/datasets/{filter}`

### ISSUE THREAD

**Issue by phaumer** [zowe/explorer-server#17]
The Explorer API mentions in the swagger documentation `/api/v1/datasets/{filter}` that it support wildcards such as `**.COBOL`. I am not able to make this work and get 500 errors. 

Are there knows issues around that? I would at expect error messages if I am using the wrong syntax.

**Comment by phaumer** [comment]
@Joe-Winchester @Colin-Stone any workarounds?

**Comment by Colin-Stone** [comment]
Just tried with https://winmvs3b.hursley.ibm.com:7949/api/v1/datasets/**.COBOL which worked fine on my installation. Does this url work if you put the equivalent of https://winmvs3b.hursley.ibm.com:7949/api/v1/datasets/USERID in?. 

Can you provide the exact uri you used please?. Also what level of Zowe. It may be that you are seeing a bigger issue as 500 represents an unexpected server error rather than an incorrect parameter etc.

**Comment by phaumer** [comment]
Using 0.9.0 (as our 0.9.3 server is down), when I try
`https://tvt4119.svl.ibm.com:7343/Atlas/api/datasets/ZOWEPH`
I get 
```json
[
  "ZOWEPH",
  "ZOWEPH.CBL",
  "ZOWEPH.D235.T1932142.ZOWEPH2",
  "ZOWEPH.D235.T1932540.ZOWEPH3",
  "ZOWEPH.ISPF.ISPPROF",
  "ZOWEPH.SAMPLE.COBCOPY",
  "ZOWEPH.SAMPLE.COBOL",
  "ZOWEPH.SAMPLE.JCL",
  "ZOWEPH.ZOEPH90"
]
```

When I try When I try 
`https://tvt4119.svl.ibm.com:7343/Atlas/api/datasets/**.COBOL` I get a 500 error.

**Comment by phaumer** [comment]
@Colin-Stone any updates? Where you able to get access to the SVL firewall?

I just tried `https://tvt4119.svl.ibm.com:7947/api/v1/datasets/**.COBOL` against 0.9.3 and got 500.

**Comment by Colin-Stone** [comment]
No. I have firewall access according the the site you apply from but I still cannot get through the firewall.

**Comment by Colin-Stone** [comment]
Got into machine and the root cause is that there is insufficient space in the catalog. 
RETURN CODE 20 Explanation: There is insufficient space in the catalog to perform the requested update or addition.

Reason Code	Description

0	Explanation: The catalog cannot be extended for one of the following reasons:
	There is no more space on the volume on which the catalog resides
	The maximum number of extents has been reached
	The catalog has reached the 4GB limit
	There is not enough contiguous space on the volume (required when the catalog’s secondary allocation is defined in tracks).
	Programmer Response: Scratch unneeded data sets from the volume. Delete all unnecessary entries from the catalog. The catalog may need to be reallocated and rebuilt if these steps do not resolve the space shortage.
So we need a SysProg to address this problem

**Comment by phaumer** [comment]
@Colin-Stone thx, we are looking into that now. 

Do you have documentation of the exact patterns supported? Is that in the ZOSMF manuals or are you providing additional capabilities? Perhaps this issue could be used to track to provide complete swagger docs if there is more to document.
